export default {
  default: 'default',
  status: 'status',
  emailConfirm: 'emailConfirm',
  signWorkQuest: 'signWorkQuest',
  restore: 'restore',
  changePassword: 'changePassword',
  addCard: 'addCard',
  deposit: 'deposit',
  cardHasBeenAdded: 'cardHasBeenAdded',
  transactionSend: 'transactionSend',
  requestSend: 'requestSend',
  privacy: 'privacy',
  withdraw: 'withdraw',
  review: 'review',
  thanks: 'Thanks ',
  confirmDetails: 'confirmDetails',
  delegate: 'delegate',
  undelegate: 'undelegate',
  showFile: 'showFile',
  inviteSend: 'inviteSend',
  openADispute: 'openADispute',
  addDiscussion: 'addDiscussion',
  changePassInSettings: 'changePassInSettings',
  addCase: 'addCase',
  transfer: 'transfer',
  twoFAAuth: 'twoFAAuth',
  addProposal: 'addProposal',
  warning: 'warning',
};
